title: Stergios Christodoulidis
description: Stergios Christodoulidis Homepage
url: "http://stergioc.github.io"

plugins: ['jekyll-twitter-plugin']
collections:
  news:
    output: true
  research:
    output: true
  publications:
    output: true
